import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import dynamic from "next/dynamic";

const Map = dynamic(
  () => {
    return import("../components/Map");
  },
  { ssr: false }
);
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Accueil - Hub Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="img/light-bulb_icon_small.png" />
      </Head>
      <div className={styles.container}>
        <Map />
      </div>
    </div>
  );
}
