import Head from "next/head";
import styles from "../styles/Home.module.css";
import * as mapData from "../public/data/dummydata.json";
import dynamic from "next/dynamic";
import Quizz from "../components/Quizz";
import { useState } from "react";
import Modal from "../components/Modal";

const Map = dynamic(
  () => {
    return import("../components/Map");
  },
  { ssr: false }
);
export default function Home() {
  const [showModal, setShowModal] = useState(false);
  const [mapUrl, setMapUrl] = useState(mapData.tilesMaps.landscapeMap.mapUrl);

  const [mapId, setMapId] = useState("landscapeMap");
  // const [mapId, setMapId] = useState("watercolorMap");
  return (
    <div className={styles.container}>
      <Head>
        <title>Accueil - Hub Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="images/light-bulb_icon_small.png" />
      </Head>
      <div className={styles.container}>
        <Map
          setShowModal={setShowModal}
          showModal={showModal}
          mapUrl={mapUrl}
          setMapUrl={setMapUrl}
          mapId={mapId}
          setMapId={setMapId}
        />

        <Modal showModal={showModal} setShowModal={setShowModal} />
      </div>
    </div>
  );
}
